# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building..."
- stage: Test1
  dependsOn: Build
  jobs:
  - job: Test1
    steps:
    - script: echo "Running tests 1..."
- stage: Test2
  dependsOn: Build
  jobs:
  - job: Test2
    steps:
    - script: echo "Running tests 2..."
- stage: Deploy
  dependsOn: 
  - Test1
  - Test2
  jobs:
  - job: Deploy
    steps:
    - script: echo "Deploying..."